RAJ RAUNAK KUMAR 20HCS4148

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix

# Step 1: Load and Prepare the Dataset
# Dataset ko load aur prepare karna
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')  # CSV se data load karna
X = dataset.drop('species', axis=1)  # Features ko alag karna (species ko hata kar)
y = dataset['species']  # Target variable ko define karna (species)

# Step 2: Split the Dataset
# Dataset ko training aur testing set mein divide karna
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # 80-20 split

# Step 3: Train the Gaussian Naive Bayes Classifier
# Gaussian Naive Bayes classifier ko train karna
naive_bayes_classifier = GaussianNB()  # Classifier ko initialize karna
naive_bayes_classifier.fit(X_train, y_train)  # Training data par classifier ko train karna

# Step 4: Predict and Evaluate
# Training aur testing set par prediction karna aur evaluation karna
y_pred_train = naive_bayes_classifier.predict(X_train)  # Training set par prediction
y_pred_test = naive_bayes_classifier.predict(X_test)  # Testing set par prediction

# Calculate Accuracy
# Accuracy ko calculate karna
train_accuracy = accuracy_score(y_train, y_pred_train)  # Training set ki accuracy
test_accuracy = accuracy_score(y_test, y_pred_test)  # Testing set ki accuracy

# Display Accuracy and Confusion Matrix
# Accuracy aur Confusion Matrix ko display karna
print("Training Accuracy:", train_accuracy)  # Training accuracy ka output
print("Testing Accuracy:", test_accuracy)  # Testing accuracy ka output
print("Confusion Matrix:")  # Confusion matrix ka output
print(confusion_matrix(y_test, y_pred_test))  # Confusion matrix ko display karna


Training Accuracy: 0.95
Testing Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
