RAJ RAUNAK KUMAR20HCS4148

In [1]:
# Zaroori libraries ko import karna
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

# Iris dataset ko load karna
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target labels

# Dataset ko training, validation, aur testing sets mein divide karna
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70-30 split
X_val, X_test, y_val, y_test = train_test_split(X_test, y_test, test_size=0.5, random_state=42)  # Validation aur testing ko 50-50 split

# Dataset ko normalize karna
scaler = StandardScaler()  # StandardScaler ka object banate hain
X_train_norm = scaler.fit_transform(X_train)  # Training set ko normalize karna
X_val_norm = scaler.transform(X_val)  # Validation set ko normalize karna
X_test_norm = scaler.transform(X_test)  # Testing set ko normalize karna

# Sabse acchi k value dhundhna
best_k = 0
best_accuracy = 0
for k in range(1, 26):  # 1 se 25 tak k ko test karna
    knn = KNeighborsClassifier(n_neighbors=k)  # KNN classifier ko banate hain
    knn.fit(X_train_norm, y_train)  # Classifier ko training set par train karna
    val_accuracy = accuracy_score(y_val, knn.predict(X_val_norm))  # Validation accuracy ko measure karna
    if val_accuracy > best_accuracy:  # Agar yeh best se zyada hai
        best_k = k  # Yeh best k hai
        best_accuracy = val_accuracy  # Best accuracy update karna

print(f"Best value of k: {best_k}")

# Best k ke sath model ko train karna
knn = KNeighborsClassifier(n_neighbors=best_k)  # Best k ke sath KNN classifier
knn.fit(X_train_norm, y_train)  # Classifier ko training set par train karna

# Model ka evaluation karna
train_accuracy = accuracy_score(y_train, knn.predict(X_train_norm))  # Training set ki accuracy
val_accuracy = accuracy_score(y_val, knn.predict(X_val_norm))  # Validation set ki accuracy
test_accuracy = accuracy_score(y_test, knn.predict(X_test_norm))  # Testing set ki accuracy

print(f"Training Accuracy: {train_accuracy:.2f}")  # Training accuracy ko print karna
print(f"Validation Accuracy: {val_accuracy:.2f}")  # Validation accuracy ko print karna
print(f"Testing Accuracy: {test_accuracy:.2f}")  # Testing accuracy ko print karna

# Confusion matrix ko display karna
train_cm = confusion_matrix(y_train, knn.predict(X_train_norm))  # Training set ka confusion matrix
val_cm = confusion_matrix(y_val, knn.predict(X_val_norm))  # Validation set ka confusion matrix
test_cm = confusion_matrix(y_test, knn.predict(X_test_norm))  # Testing set ka confusion matrix

print("Training Confusion Matrix:")  # Training set ka confusion matrix
print(train_cm)  # Display training confusion matrix
print("\nValidation Confusion Matrix:")  # Validation set ka confusion matrix
print(val_cm)  # Display validation confusion matrix
print("\nTesting Confusion Matrix:")  # Testing set ka confusion matrix
print(test_cm)  # Display testing confusion matrix


Best value of k: 1
Training Accuracy: 1.00
Validation Accuracy: 1.00
Testing Accuracy: 0.96
Training Confusion Matrix:
[[31  0  0]
 [ 0 37  0]
 [ 0  0 37]]

Validation Confusion Matrix:
[[13  0  0]
 [ 0  3  0]
 [ 0  0  6]]

Testing Confusion Matrix:
[[6 0 0]
 [0 9 1]
 [0 0 7]]
